module.exports= [{
        "id": "1",
        "sortname": "AF",
        "name": "Afghanistan",
        "phonecode": "93",
        "symbol": "Af",
		"currencyName": "Afghan Afghani",
    }, {
        "id": "2",
        "sortname": "AL",
        "name": "Albania",
        "phonecode": "355",
        "symbol": "ALL",
		"currencyName": "Albanian Lek",
    }, {
        "id": "3",
        "sortname": "DZ",
        "name": "Algeria",
        "phonecode": "213",
        "symbol": "DA",
		"currencyName": "Algerian Dinar",
    }, {
        "id": "4",
        "sortname": "AS",
        "name": "American Samoa",
        "phonecode": "1684",
        "symbol": "$",
		"currencyName": "US Dollar",
	
    }, {
        "id": "5",
        "sortname": "AD",
        "name": "Andorra",
        "phonecode": "376",
        "symbol": "€",
		"currencyName": "Euro",
    }, {
        "id": "6",
        "sortname": "AO",
        "name": "Angola",
        "phonecode": "244",
    }, {
        "id": "7",
        "sortname": "AI",
        "name": "Anguilla",
        "phonecode": "1264"
    }, {
        "id": "8",
        "sortname": "AQ",
        "name": "Antarctica",
        "phonecode": "0",
        "symbol": "€",
		"currencyName": "Euro",
    }, {
        "id": "9",
        "sortname": "AG",
        "name": "Antigua And Barbuda",
        "phonecode": "1268",
    }, {
        "id": "10",
        "sortname": "AR",
        "name": "Argentina",
        "phonecode": "54",
        "symbol": "AR$",
		"currencyName": "Argentine Peso"
    }, {
        "id": "11",
        "sortname": "AM",
        "name": "Armenia",
        "phonecode": "374",
        "symbol": "AMD",
		"currencyName": "Armenian Dram",
    }, {
        "id": "12",
        "sortname": "AW",
        "name": "Aruba",
        "phonecode": "297",
    }, {
        "id": "13",
        "sortname": "AU",
        "name": "Australia",
        "phonecode": "61",
        "symbol": "AU$",
		"currencyName": "Australian Dollar",
    }, {
        "id": "14",
        "sortname": "AT",
        "name": "Austria",
        "phonecode": "43",
        "symbol": "€",
		"currencyName": "Euro",
    }, {
        "id": "15",
        "sortname": "AZ",
        "name": "Azerbaijan",
        "phonecode": "994",
        "symbol": "man.",
		"currencyName": "Azerbaijani Manat",
    }, {
        "id": "16",
        "sortname": "BS",
        "name": "Bahamas The",
        "phonecode": "1242"
    }, {
        "id": "17",
        "sortname": "BH",
        "name": "Bahrain",
        "phonecode": "973",
        "symbol": "BD",
		"currencyName": "Bahraini Dinar",
    }, {
        "id": "18",
        "sortname": "BD",
        "name": "Bangladesh",
        "phonecode": "880",
        "symbol": "Tk",
		"currencyName": "Bangladeshi Taka",
    }, {
        "id": "19",
        "sortname": "BB",
        "name": "Barbados",
        "phonecode": "1246",
        "symbol": "Bds$",
		"currencyName": "Barbadian Dollar",
    }, {
        "id": "20",
        "sortname": "BY",
        "name": "Belarus",
        "phonecode": "375",
        "symbol": "Br",
		"currencyName": "Belarusian Ruble",
    }, {
        "id": "21",
        "sortname": "BE",
        "name": "Belgium",
        "phonecode": "32",
        "symbol": "€",
		"currencyName": "Euro",
    }, {
        "id": "22",
        "sortname": "BZ",
        "name": "Belize",
        "phonecode": "501",
        "symbol": "BZ$",
		"currencyName": "Belize Dollar",
    }, {
        "id": "23",
        "sortname": "BJ",
        "name": "Benin",
        "phonecode": "229",
        "symbol": "CFA",
		"currencyName": "West African CFA franc",
    }, {
        "id": "24",
        "sortname": "BM",
        "name": "Bermuda",
        "phonecode": "1441",
        "symbol": "BMD",
		"currencyName": "Bermudian Dollar",
    }, {
        "id": "25",
        "sortname": "BT",
        "name": "Bhutan",
        "phonecode": "975",
        "symbol": "BTN",
		"currencyName": "Bhutanese Ngultrum",
    }, {
        "id": "26",
        "sortname": "BO",
        "name": "Bolivia",
        "phonecode": "591",
        "symbol": "Bs",
		"currencyName": "Bolivian Boliviano",
    }, {
        "id": "27",
        "sortname": "BA",
        "name": "Bosnia and Herzegovina",
        "phonecode": "387",
        "symbol": "KM",
		"currencyName": "Bosnia-Herzegovina Convertible Mark",
    }, {
        "id": "28",
        "sortname": "BW",
        "name": "Botswana",
        "phonecode": "267",
        "symbol": "BWP",
		"currencyName": "pula",
    }, {
        "id": "29",
        "sortname": "BV",
        "name": "Bouvet Island",
        "phonecode": "0",
        "symbol": "KR",
		"currencyName": "Krone",
    }, {
        "id": "30",
        "sortname": "BR",
        "name": "Brazil",
        "phonecode": "55",
        "symbol": "R$",
		"currencyName": "Brazilian Real",
    }, {
        "id": "31",
        "sortname": "IO",
        "name": "British Indian Ocean Territory",
        "phonecode": "246"
    }, {
        "id": "32",
        "sortname": "BN",
        "name": "Brunei",
        "phonecode": "673",
        "symbol": "BN$",
		"currencyName": "Brunei Dollar",
    }, {
        "id": "33",
        "sortname": "BG",
        "name": "Bulgaria",
        "phonecode": "359",
        "symbol": "BGN",
		"currencyName": "Bulgarian Lev",

    }, {
        "id": "34",
        "sortname": "BF",
        "name": "Burkina Faso",
        "phonecode": "226"
        
    }, {
        "id": "35",
        "sortname": "BI",
        "name": "Burundi",
        "phonecode": "257",
        "symbol": "FBu",
		"currencyName": "Burundian Franc",
    }, {
        "id": "36",
        "sortname": "KH",
        "name": "Cambodia",
        "phonecode": "855",
        "symbol": "KHR",
		"currencyName": "Cambodian Riel",
    }, {
        "id": "37",
        "sortname": "CM",
        "name": "Cameroon",
        "phonecode": "237"
       
    }, {
        "id": "38",
        "sortname": "CA",
        "name": "Canada",
        "phonecode": "1",
        "symbol": "CA$",
		"currencyName": "Canadian Dollar",
    }, {
        "id": "39",
        "sortname": "CV",
        "name": "Cape Verde",
        "phonecode": "238",
        "symbol": "CV$",
		"currencyName": "Cape Verdean Escudo",

    }, {
        "id": "40",
        "sortname": "KY",
        "name": "Cayman Islands",
        "phonecode": "1345",
        "symbol": "KYD",
		"currencyName": "Caymanian Dollar",
    }, {
        "id": "41",
        "sortname": "CF",
        "name": "Central African Republic",
        "phonecode": "236",
        "symbol": "XAF",
		"currencyName": "Central African CFA franc",
    }, {
        "id": "42",
        "sortname": "TD",
        "name": "Chad",
        "phonecode": "235"
    }, {
        "id": "43",
        "sortname": "CL",
        "name": "Chile",
        "phonecode": "56",
        "symbol": "CL$",
		"currencyName": "Chilean Peso",
    }, {
        "id": "44",
        "sortname": "CN",
        "name": "China",
        "phonecode": "86",
        "symbol": "CN¥",
		"currencyName": "Chinese Yuan",
    }, {
        "id": "45",
        "sortname": "CX",
        "name": "Christmas Island",
        "phonecode": "61",
        "symbol": "AU$",
		"currencyName": "Australian Dollar",
    }, {
        "id": "46",
        "sortname": "CC",
        "name": "Cocos (Keeling) Islands",
        "phonecode": "672",
        "symbol": "AU$",
		"currencyName": "Australian Dollar",
    }, {
        "id": "47",
        "sortname": "CO",
        "name": "Colombia",
        "phonecode": "57",
        "symbol": "CO$",
		"currencyName": "Colombian Peso",
    }, {
        "id": "48",
        "sortname": "KM",
        "name": "Comoros",
        "phonecode": "269",
        "symbol": "CF",
		"currencyName": "Comorian Franc",
    }, {
        "id": "49",
        "sortname": "CG",
        "name": "Congo",
        "phonecode": "242",
        "symbol": "CDF",
		"currencyName": "Congolese Franc",
    }, {
        "id": "50",
        "sortname": "CD",
        "name": "Congo The Democratic Republic Of The",
        "phonecode": "242",
        "symbol": "CDF",
		"currencyName": "Congolese Franc",
    }, {
        "id": "51",
        "sortname": "CK",
        "name": "Cook Islands",
        "phonecode": "682",
        "symbol": "NZ$",
		"currencyName": "New Zealand Dollar",
    }, {
        "id": "52",
        "sortname": "CR",
        "name": "Costa Rica",
        "phonecode": "506",
        "symbol": "₡",
		"currencyName": "Costa Rican Colón",

    }, {
        "id": "53",
        "sortname": "CI",
        "name": "Cote D''Ivoire (Ivory Coast)",
        "phonecode": "225"

    }, {
        "id": "54",
        "sortname": "HR",
        "name": "Croatia (Hrvatska)",
        "phonecode": "385",
        "symbol": "kn",
		"currencyName": "Croatian Kuna",
    }, {
        "id": "55",
        "sortname": "CU",
        "name": "Cuba",
        "phonecode": "53",
        "symbol": "CUP",
		"currencyName": "Cuban peso",
    }, {
        "id": "56",
        "sortname": "CY",
        "name": "Cyprus",
        "phonecode": "357",
        "symbol": "€",
		"currencyName": "Euro",

    }, {
        "id": "57",
        "sortname": "CZ",
        "name": "Czech Republic",
        "phonecode": "420",
        "symbol": "CZK",
		"currencyName": "Czech koruna",
    }, {
        "id": "58",
        "sortname": "DK",
        "name": "Denmark",
        "phonecode": "45",
        "symbol": "Dkr",
		"currencyName": "Danish Krone",
        
    }, {
        "id": "59",
        "sortname": "DJ",
        "name": "Djibouti",
        "phonecode": "253",
        "symbol": "Fdj",
		"currencyName": "Djiboutian Franc",
    }, {
        "id": "60",
        "sortname": "DM",
        "name": "Dominica",
        "phonecode": "1767"
    }, {
        "id": "61",
        "sortname": "DO",
        "name": "Dominican Republic",
        "phonecode": "1809",
        "symbol": "RD$",
		"currencyName": "Dominican Peso",
    }, {
        "id": "62",
        "sortname": "TP",
        "name": "East Timor",
        "phonecode": "670",
        "symbol": "$",
		"currencyName": "United States Dollar",
    }, {
        "id": "63",
        "sortname": "EC",
        "name": "Ecuador",
        "phonecode": "593",
        "symbol": "$",
		"currencyName": "United States Dollar",
    }, {
        "id": "64",
        "sortname": "EG",
        "name": "Egypt",
        "phonecode": "20",
        "symbol": "EGP",
		"currencyName": "Egyptian Pound",
    }, {
        "id": "65",
        "sortname": "SV",
        "name": "El Salvador",
        "phonecode": "503",
        "symbol": "$",
		"currencyName": "United States Dollar",
    }, {
        "id": "66",
        "sortname": "GQ",
        "name": "Equatorial Guinea",
        "phonecode": "240"
    }, {
        "id": "67",
        "sortname": "ER",
        "name": "Eritrea",
        "phonecode": "291",
        "symbol": "Nfk",
		"currencyName": "Eritrean Nakfa",
    }, {
        "id": "68",
        "sortname": "EE",
        "name": "Estonia",
        "phonecode": "372",
        "symbol": "€",
		"currencyName": "Euro",
    }, {
        "id": "69",
        "sortname": "ET",
        "name": "Ethiopia",
        "phonecode": "251",
        "symbol": "Br",
		"currencyName": "Ethiopian Birr",
    }, {
        "id": "70",
        "sortname": "XA",
        "name": "External Territories of Australia",
        "phonecode": "61"
    }, {
        "id": "71",
        "sortname": "FK",
        "name": "Falkland Islands",
        "phonecode": "500",
        "symbol": "FKP",
		"currencyName": "Falkland Island Pound",
    }, {
        "id": "72",
        "sortname": "FO",
        "name": "Faroe Islands",
        "phonecode": "298"
    }, {
        "id": "73",
        "sortname": "FJ",
        "name": "Fiji Islands",
        "phonecode": "679",
        "symbol": " FJ$",
		"currencyName": "Fijian dollar",
    }, {
        "id": "74",
        "sortname": "FI",
        "name": "Finland",
        "phonecode": "358",
        "symbol": "€",
		"currencyName": "Euro",

    }, {
        "id": "75",
        "sortname": "FR",
        "name": "France",
        "phonecode": "33",
        "symbol": "XPF",
		"currencyName": "CFP Franc",
    }, {
        "id": "76",
        "sortname": "GF",
        "name": "French Guiana",
        "phonecode": "594",
        "symbol": "€",
		"currencyName": "Euro",
    }, {
        "id": "77",
        "sortname": "PF",
        "name": "French Polynesia",
        "phonecode": "689",
        "symbol": "XPF",
		"currencyName": "CFP Franc",
    }, {
        "id": "78",
        "sortname": "TF",
        "name": "French Southern Territories",
        "phonecode": "0"
    }, {
        "id": "79",
        "sortname": "GA",
        "name": "Gabon",
        "phonecode": "241",
        "symbol": "XAF",
		"currencyName": "Central African CFA franc",
    }, {
        "id": "80",
        "sortname": "GM",
        "name": "Gambia The",
        "phonecode": "220",
        "symbol": "D",
		"currencyName": "Gambian dalasi",
    }, {
        "id": "81",
        "sortname": "GE",
        "name": "Georgia",
        "phonecode": "995",
        "symbol": "GEL",
		"currencyName": "Georgian Lari",
    }, {
        "id": "82",
        "sortname": "DE",
        "name": "Germany",
        "phonecode": "49",
        "symbol": "€",
		"currencyName": "Euro",

    }, {
        "id": "83",
        "sortname": "GH",
        "name": "Ghana",
        "phonecode": "233",
        "symbol": "GH₵",
		"currencyName": "Ghanaian Cedi",
    }, {
        "id": "84",
        "sortname": "GI",
        "name": "Gibraltar",
        "phonecode": "350",
        "symbol": "£G",
		"currencyName": "Gibraltar Pound",
        
    }, {
        "id": "85",
        "sortname": "GR",
        "name": "Greece",
        "phonecode": "30",
        "symbol": "€",
		"currencyName": "Euro",
    }, {
        "id": "86",
        "sortname": "GL",
        "name": "Greenland",
        "phonecode": "299",
        "symbol": "Dkr",
		"currencyName": "Danish Krone",
    }, {
        "id": "87",
        "sortname": "GD",
        "name": "Grenada",
        "phonecode": "1473",
        "symbol": "EC$",
		"currencyName": "Eastern Caribbean dollar",
    }, {
        "id": "88",
        "sortname": "GP",
        "name": "Guadeloupe",
        "phonecode": "590",
        "symbol": "€",
		"currencyName": "Euro",

    }, {
        "id": "89",
        "sortname": "GU",
        "name": "Guam",
        "phonecode": "1671",
        "symbol": "$",
		"currencyName": "US Dollar",
    }, {
        "id": "90",
        "sortname": "GT",
        "name": "Guatemala",
        "phonecode": "502",
        "symbol": "GTQ",
		"currencyName": "Guatemalan Quetzal",
    }, {
        "id": "91",
        "sortname": "XU",
        "name": "Guernsey and Alderney",
        "phonecode": "44"
    }, {
        "id": "92",
        "sortname": "GN",
        "name": "Guinea",
        "phonecode": "224",
        "symbol": "FG",
		"currencyName": "Guinean Franc",
    }, {
        "id": "93",
        "sortname": "GW",
        "name": "Guinea-Bissau",
        "phonecode": "245",
        "symbol": "CFA",
		"currencyName": "West African CFA franc",
    }, {
        "id": "94",
        "sortname": "GY",
        "name": "Guyana",
        "phonecode": "592",
        "symbol": "G$",
		"currencyName": "Guyanese dollar",
    }, {
        "id": "95",
        "sortname": "HT",
        "name": "Haiti",
        "phonecode": "509",
        "symbol": "G",
		"currencyName": "Haitian gourde",
    }, {
        "id": "96",
        "sortname": "HM",
        "name": "Heard and McDonald Islands",
        "phonecode": "0",
        "symbol": "AU$",
		"currencyName": "Australian Dollar",
    }, {
        "id": "97",
        "sortname": "HN",
        "name": "Honduras",
        "phonecode": "504",
        "symbol": "HNL",
		"currencyName": "Honduran Lempira",
    }, {
        "id": "98",
        "sortname": "HK",
        "name": "Hong Kong S.A.R.",
        "phonecode": "852",
        "symbol": "HK$",
		"currencyName": "Hong Kong Dollar",
    }, {
        "id": "99",
        "sortname": "HU",
        "name": "Hungary",
        "phonecode": "36",
        "symbol": "Ft",
		"currencyName": "Hungarian Forint",
    }, {
        "id": "100",
        "sortname": "IS",
        "name": "Iceland",
        "phonecode": "354",
        "symbol": "Ikr",
		"currencyName": "Icelandic Króna",
    }, {
        "id": "101",
        "sortname": "IN",
        "name": "India",
        "phonecode": "91",
        "symbol": "Rs",
		"currencyName": "Indian Rupee",
    }, {
        "id": "102",
        "sortname": "ID",
        "name": "Indonesia",
        "phonecode": "62",
        "symbol": "Rp",
		"currencyName": "Indonesian Rupiah",
    }, {
        "id": "103",
        "sortname": "IR",
        "name": "Iran",
        "phonecode": "98",
        "symbol": "IRR",
		"currencyName": "Iranian Rial",
    }, {
        "id": "104",
        "sortname": "IQ",
        "name": "Iraq",
        "phonecode": "964",
        "symbol": "IQD",
		"currencyName": "Iraqi Dinar",
    }, {
        "id": "105",
        "sortname": "IE",
        "name": "Ireland",
        "phonecode": "353",
        "symbol": "€",
		"currencyName": "Euro",
    }, {
        "id": "106",
        "sortname": "IL",
        "name": "Israel",
        "phonecode": "972",
        "symbol": "₪",
		"currencyName": "Israeli New Sheqel",

    }, {
        "id": "107",
        "sortname": "IT",
        "name": "Italy",
        "phonecode": "39",
        "symbol": "€",
		"currencyName": "Euro",

    }, {
        "id": "108",
        "sortname": "JM",
        "name": "Jamaica",
        "phonecode": "1876",
        "symbol": "J$",
		"currencyName": "Jamaican Dollar",
    }, {
        "id": "109",
        "sortname": "JP",
        "name": "Japan",
        "phonecode": "81",
        "symbol": "¥",
		"currencyName": "Japanese Yen",
    }, {
        "id": "110",
        "sortname": "XJ",
        "name": "Jersey",
        "phonecode": "44",
        "symbol": "JEP",
		"currencyName": "Jersey Pound",
    }, {
        "id": "111",
        "sortname": "JO",
        "name": "Jordan",
        "phonecode": "962",
        "symbol": "JD",
		"currencyName": "Jordanian Dinar",
    }, {
        "id": "112",
        "sortname": "KZ",
        "name": "Kazakhstan",
        "phonecode": "7",
        "symbol": "KZT",
		"currencyName": "Kazakhstani Tenge",
    }, {
        "id": "113",
        "sortname": "KE",
        "name": "Kenya",
        "phonecode": "254",
        "symbol": "Ksh",
		"currencyName": "Kenyan Shilling",
    }, {
        "id": "114",
        "sortname": "KI",
        "name": "Kiribati",
        "phonecode": "686"
    }, {
        "id": "115",
        "sortname": "KP",
        "name": "Korea North",
        "phonecode": "850",
        "symbol": "KPW",
		"currencyName": "North Korean won",
    }, {
        "id": "116",
        "sortname": "KR",
        "name": "Korea South",
        "phonecode": "82",
        "symbol": "₩",
		"currencyName": "South Korean Won",
    }, {
        "id": "117",
        "sortname": "KW",
        "name": "Kuwait",
        "phonecode": "965",
        "symbol": "KD",
		"currencyName": "Kuwaiti Dinar",
    }, {
        "id": "118",
        "sortname": "KG",
        "name": "Kyrgyzstan",
        "phonecode": "996",
        "symbol": "Лв",
		"currencyName": "Kyrgyzstani som",
    }, {
        "id": "119",
        "sortname": "LA",
        "name": "Laos",
        "phonecode": "856",
        "symbol": "₭N",
		"currencyName": "Lao kip",
    }, {
        "id": "120",
        "sortname": "LV",
        "name": "Latvia",
        "phonecode": "371",
        "symbol": "Ls",
		"currencyName": "Latvian Lats",
    }, {
        "id": "121",
        "sortname": "LB",
        "name": "Lebanon",
        "phonecode": "961",
        "symbol": "LB£",
		"currencyName": "Lebanese Pound",
    }, {
        "id": "122",
        "sortname": "LS",
        "name": "Lesotho",
        "phonecode": "266",
        "symbol": "R",
		"currencyName": "South African Rand",
    }, {
        "id": "123",
        "sortname": "LR",
        "name": "Liberia",
        "phonecode": "231",
        "symbol": "LD$",
		"currencyName": "Liberian dollar",
    }, {
        "id": "124",
        "sortname": "LY",
        "name": "Libya",
        "phonecode": "218",
        "symbol": "LD",
		"currencyName": "Libyan Dinar",

    }, {
        "id": "125",
        "sortname": "LI",
        "name": "Liechtenstein",
        "phonecode": "423",
        "symbol": "CHF",
		"currencyName": "Swiss Franc",
    }, {
        "id": "126",
        "sortname": "LT",
        "name": "Lithuania",
        "phonecode": "370",
        "symbol": "€",
		"currencyName": "Euro",
    }, {
        "id": "127",
        "sortname": "LU",
        "name": "Luxembourg",
        "phonecode": "352",
        "symbol": "€",
		"currencyName": "Euro",
    }, {
        "id": "128",
        "sortname": "MO",
        "name": "Macau S.A.R.",
        "phonecode": "853",
        "symbol": "MOP$",
		"currencyName": "Macanese Pataca",
    }, {
        "id": "129",
        "sortname": "MK",
        "name": "Macedonia",
        "phonecode": "389",
        "symbol": "MKD",
		"currencyName": "Macedonian Denar",
    }, {
        "id": "130",
        "sortname": "MG",
        "name": "Madagascar",
        "phonecode": "261",
        "symbol": "MGA",
		"currencyName": "Malagasy Ariary",
    }, {
        "id": "131",
        "sortname": "MW",
        "name": "Malawi",
        "phonecode": "265",
        "symbol": "MK",
		"name": "Malawian Kwacha",
    }, {
        "id": "132",
        "sortname": "MY",
        "name": "Malaysia",
        "phonecode": "60",
        "symbol": "RM",
		"currencyName": "Malaysian Ringgit",
    }, {
        "id": "133",
        "sortname": "MV",
        "name": "Maldives",
        "phonecode": "960"
    }, {
        "id": "134",
        "sortname": "ML",
        "name": "Mali",
        "phonecode": "223",
        "symbol": "CFA",
		"currencyName": "West African CFA franc",
    }, {
        "id": "135",
        "sortname": "MT",
        "name": "Malta",
        "phonecode": "356",
        "symbol": "€",
		"currencyName": "Euro",
    }, {
        "id": "136",
        "sortname": "XM",
        "name": "Man (Isle of)",
        "phonecode": "44",
        "symbol": "€",
		"currencyName": "pound sterling",
    }, {
        "id": "137",
        "sortname": "MH",
        "name": "Marshall Islands",
        "phonecode": "692",
        "symbol": "$",
		"currencyName": "US Dollar",
    }, {
        "id": "138",
        "sortname": "MQ",
        "name": "Martinique",
        "phonecode": "596",
        "symbol": "€",
		"currencyName": "Euro",
    }, {
        "id": "139",
        "sortname": "MR",
        "name": "Mauritania",
        "phonecode": "222"
    }, {
        "id": "140",
        "sortname": "MU",
        "name": "Mauritius",
        "phonecode": "230",
        "symbol": "MURs",
		"currencyName": "Mauritian Rupee",
    }, {
        "id": "141",
        "sortname": "YT",
        "name": "Mayotte",
        "phonecode": "269",
        "symbol": "€",
		"currencyName": "Euro",
    }, {
        "id": "142",
        "sortname": "MX",
        "name": "Mexico",
        "phonecode": "52",
        "symbol": "MX$",
		"currencyName": "Mexican Peso",
    }, {
        "id": "143",
        "sortname": "FM",
        "name": "Micronesia",
        "phonecode": "691",
        "symbol": "$",
		"currencyName": "US Dollar",
    }, {
        "id": "144",
        "sortname": "MD",
        "name": "Moldova",
        "phonecode": "373",
        "symbol": "MDL",
		"currencyName": "Moldovan Leu",
    }, {
        "id": "145",
        "sortname": "MC",
        "name": "Monaco",
        "phonecode": "377",
        "symbol": "€",
		"currencyName": "Euro",
    }, {
        "id": "146",
        "sortname": "MN",
        "name": "Mongolia",
        "phonecode": "976",
        "symbol": "₮",
		"currencyName": "Mongolian tögrög",

    }, {
        "id": "147",
        "sortname": "MS",
        "name": "Montserrat",
        "phonecode": "1664",
        "symbol": "$",
		"currencyName": "Eastern Caribbean dollar",
    }, {
        "id": "148",
        "sortname": "MA",
        "name": "Morocco",
        "phonecode": "212",
        "symbol": "MAD",
		"currencyName": "Moroccan Dirham",

    }, {
        "id": "149",
        "sortname": "MZ",
        "name": "Mozambique",
        "phonecode": "258",
        "symbol": "MTn",
		"currencyName": "Mozambican Metical",
    }, {
        "id": "150",
        "sortname": "MM",
        "name": "Myanmar",
        "phonecode": "95",
        "symbol": "K",
		"currencyName": "Burmese kyat",
    }, {
        "id": "151",
        "sortname": "NA",
        "name": "Namibia",
        "phonecode": "264",
        "symbol": "N$",
		"currencyName": "Namibian Dollar",
    }, {
        "id": "152",
        "sortname": "NR",
        "name": "Nauru",
        "phonecode": "674",
        "symbol": "AU$",
		"currencyName": "Australian Dollar",
    }, {
        "id": "153",
        "sortname": "NP",
        "name": "Nepal",
        "phonecode": "977",
        "symbol": "NPRs",
		"currencyName": "Nepalese Rupee",

    }, {
        "id": "154",
        "sortname": "AN",
        "name": "Netherlands Antilles",
        "phonecode": "599"
    }, {
        "id": "155",
        "sortname": "NL",
        "name": "Netherlands The",
        "phonecode": "31",
        "symbol": "€",
		"currencyName": "Euro",
    }, {
        "id": "156",
        "sortname": "NC",
        "name": "New Caledonia", 
        "phonecode": "687",
        "symbol": "₣",
		"currencyName": "CFP franc",

    }, {
        "id": "157",
        "sortname": "NZ",
        "name": "New Zealand",
        "phonecode": "64",
        "symbol": "NZ$",
		"currencyName": "New Zealand Dollar",
    }, {
        "id": "158",
        "sortname": "NI",
        "name": "Nicaragua",
        "phonecode": "505",
        "symbol": "C$",
		"currencyName": "Nicaraguan Córdoba",
    }, {
        "id": "159",
        "sortname": "NE",
        "name": "Niger",
        "phonecode": "227",
        "symbol": "CFA",
		"currencyName": "West African CFA franc",
    }, {
        "id": "160",
        "sortname": "NG",
        "name": "Nigeria",
        "phonecode": "234",
        "symbol": "₦",
		"currencyName": "Nigerian Naira",
    }, {
        "id": "161",
        "sortname": "NU",
        "name": "Niue",
        "phonecode": "683",
        "symbol": "NZ$",
		"currencyName": "New Zealand Dollar",

    }, {
        "id": "162",
        "sortname": "NF",
        "name": "Norfolk Island",
        "phonecode": "672",
        "symbol": "AU$",
		"currencyName": "Australian Dollar",
    }, {
        "id": "163",
        "sortname": "MP",
        "name": "Northern Mariana Islands",
        "phonecode": "1670",
        "symbol": "$",
		"currencyName": "US Dollar",
    }, {
        "id": "164",
        "sortname": "NO",
        "name": "Norway",
        "phonecode": "47",
        "symbol": "Nkr",
		"currencyName": "Norwegian Krone",
    }, {
        "id": "165",
        "sortname": "OM",
        "name": "Oman",
        "phonecode": "968",
        "symbol": "OMR",
		"currencyName": "Omani Rial",
    }, {
        "id": "166",
        "sortname": "PK",
        "name": "Pakistan",
        "phonecode": "92",
        "symbol": "PKRs",
		"currencyName": "Pakistani Rupee",

    }, {
        "id": "167",
        "sortname": "PW",
        "name": "Palau",
        "phonecode": "680",
        "symbol": "$",
		"currencyName": "US Dollar",

    }, {
        "id": "168",
        "sortname": "PS",
        "name": "Palestinian Territory Occupied",
        "phonecode": "970"
    }, {
        "id": "169",
        "sortname": "PA",
        "name": "Panama",
        "phonecode": "507",
        "symbol": "$",
		"currencyName": "US Dollar",
    }, {
        "id": "170",
        "sortname": "PG",
        "name": "Papua new Guinea",
        "phonecode": "675",
        "symbol": "K",
		"currencyName": "Kina",
    }, {
        "id": "171",
        "sortname": "PY",
        "name": "Paraguay",
        "phonecode": "595",
        "symbol": "₲",
		"currencyName": "Paraguayan Guarani",
    }, {
        "id": "172",
        "sortname": "PE",
        "name": "Peru",
        "phonecode": "51",
        "symbol": "S/.",
		"currencyName": "Peruvian Nuevo Sol",
    }, {
        "id": "173",
        "sortname": "PH",
        "name": "Philippines",
        "phonecode": "63",
        "symbol": "₱",
		"currencyName": "Philippine Peso",
    }, {
        "id": "174",
        "sortname": "PN",
        "name": "Pitcairn Island",
        "phonecode": "0",
        "symbol": "NZ$",
		"currencyName": "New Zealand Dollar",
    }, {
        "id": "175",
        "sortname": "PL",
        "name": "Poland",
        "phonecode": "48",
        "symbol": "zł",
		"currencyName": "Polish Zloty",
    }, {
        "id": "176",
        "sortname": "PT",
        "name": "Portugal",
        "phonecode": "351",
        "symbol": "€",
		"currenyName": "Euro",
    }, {
        "id": "177",
        "sortname": "PR",
        "name": "Puerto Rico",
        "phonecode": "1787",
        "symbol": "$",
		"currencyName": "US Dollar",
      
    }, {
        "id": "178",
        "sortname": "QA",
        "name": "Qatar",
        "phonecode": "974",
        "symbol": "ر.ق",
		"currencyName": "Qatari riyal",
    }, {
        "id": "179",
        "sortname": "RE",
        "name": "Reunion",
        "phonecode": "262",
        "symbol": "€",
		"currencyName": "Euro",
    }, {
        "id": "180",
        "sortname": "RO",
        "name": "Romania",
        "phonecode": "40",
        "symbol": "RON",
		"currencyName": "Romanian Leu",
    }, {
        "id": "181",
        "sortname": "RU",
        "name": "Russia",
        "phonecode": "70",
        "symbol": "RUB",
		"currencyName": "Russian Ruble",

    }, {
        "id": "182",
        "sortname": "RW",
        "name": "Rwanda",
        "phonecode": "250",
        "symbol": "RWF",
		"currencyName": "Rwandan Franc",
    }, {
        "id": "183",
        "sortname": "SH",
        "name": "Saint Helena",
        "phonecode": "290",
    }, {
        "id": "184",
        "sortname": "KN",
        "name": "Saint Kitts And Nevis",
        "phonecode": "1869",
        "symbol": "EC$",
		"currencyName": "Eastern Caribbean dollar",
    }, {
        "id": "185",
        "sortname": "LC",
        "name": "Saint Lucia",
        "phonecode": "1758",
        "symbol": "EC$",
		"currencyName": "Eastern Caribbean dollar",
    }, {
        "id": "186",
        "sortname": "PM",
        "name": "Saint Pierre and Miquelon",
        "phonecode": "508",
        "symbol": "€",
		"currencyName": "Euro",
    }, {
        "id": "187",
        "sortname": "VC",
        "name": "Saint Vincent And The Grenadines",
        "phonecode": "1784",
        "symbol": "EC$",
		"currencyName": "Eastern Caribbean dollar",
    }, {
        "id": "188",
        "sortname": "WS",
        "name": "Samoa",
        "phonecode": "684",
        "symbol": "WS$",
		"currencyName": "Samoan tālā",
    }, {
        "id": "189",
        "sortname": "SM",
        "name": "San Marino",
        "phonecode": "378",
        "symbol": "€",
		"currencyName": "Euro",
    }, {
        "id": "190",
        "sortname": "ST",
        "name": "Sao Tome and Principe",
        "phonecode": "239"
    }, {
        "id": "191",
        "sortname": "SA",
        "name": "Saudi Arabia",
        "phonecode": "966",
        "symbol": "SR",
		"currencyName": "Saudi Riyal",
    }, {
        "id": "192",
        "sortname": "SN",
        "name": "Senegal",
        "phonecode": "221",
        "symbol": "CFA",
		"currencyName": "West African CFA franc",
    }, {
        "id": "193",
        "sortname": "RS",
        "name": "Serbia",
        "phonecode": "381",
        "symbol": "din.",
		"currencyName": "Serbian Dinar",
    }, {
        "id": "194",
        "sortname": "SC",
        "name": "Seychelles",
        "phonecode": "248"
    }, {
        "id": "195",
        "sortname": "SL",
        "name": "Sierra Leone",
        "phonecode": "232"
    }, {
        "id": "196",
        "sortname": "SG",
        "name": "Singapore",
        "phonecode": "65",
        "symbol": "S$",
		"currencyName": "Singapore Dollar",
    }, {
        "id": "197",
        "sortname": "SK",
        "name": "Slovakia",
        "phonecode": "421",
        "symbol": "€",
		"currencyName": "Euro",
    }, {
        "id": "198",
        "sortname": "SI",
        "name": "Slovenia",
        "phonecode": "386",
        "symbol": "€",
		"currencyName": "Euro",
    }, {
        "id": "199",
        "sortname": "XG",
        "name": "Smaller Territories of the UK",
        "phonecode": "44",

    }, {
        "id": "200",
        "sortname": "SB",
        "name": "Solomon Islands",
        "phonecode": "677"
    }, {
        "id": "201",
        "sortname": "SO",
        "name": "Somalia",
        "phonecode": "252",
        "symbol": "$",
		"currencyName": "US Dollar",
    }, {
        "id": "202",
        "sortname": "ZA",
        "name": "South Africa",
        "phonecode": "27",
        "symbol": "R",
		"currencyName": "South African Rand",
    }, {
        "id": "203",
        "sortname": "GS",
        "name": "South Georgia",
        "phonecode": "0",
        "symbol": "GEL",
		"currencyName": "Georgian Lari",
    }, {
        "id": "204",
        "sortname": "SS",
        "name": "South Sudan",
        "phonecode": "211",
        "symbol": "SS£",
		"currencyName": "South Sudanese pound",
    }, {
        "id": "205",
        "sortname": "ES",
        "name": "Spain",
        "phonecode": "34",
        "symbol": "€",
		"currencyName": "Euro",
    }, {
        "id": "206",
        "sortname": "LK",
        "name": "Sri Lanka",
        "phonecode": "94",
        "symbol": "SLRs",
		"currencyName": "Sri Lankan Rupee",
    }, {
        "id": "207",
        "sortname": "SD",
        "name": "Sudan",
        "phonecode": "249",
        "symbol": "SDG",
		"currencyName": "Sudanese Pound",
    }, {
        "id": "208",
        "sortname": "SR",
        "name": "Suriname",
        "phonecode": "597"
    }, {
        "id": "209",
        "sortname": "SJ",
        "name": "Svalbard And Jan Mayen Islands",
        "phonecode": "47"
    }, {
        "id": "210",
        "sortname": "SZ",
        "name": "Swaziland",
        "phonecode": "268",
        "symbol": "E,L",
		"currencyName": "Swazi Lilangeni",
    }, {
        "id": "211",
        "sortname": "SE",
        "name": "Sweden",
        "phonecode": "46",
        "symbol": "Skr",
		"currencyName": "Swedish Krona",
    }, {
        "id": "212",
        "sortname": "CH",
        "name": "Switzerland",
        "phonecode": "41",
        "symbol": "CHF",
		"currencyName": "Swiss Franc",
    }, {
        "id": "213",
        "sortname": "SY",
        "name": "Syria",
        "phonecode": "963",
        "symbol": "SY£",
		"currencyName": "Syrian Pound",

    }, {
        "id": "214",
        "sortname": "TW",
        "name": "Taiwan",
        "phonecode": "886",
        "symbol": "NT$",
		"currencyName": "New Taiwan Dollar",
    }, {
        "id": "215",
        "sortname": "TJ",
        "name": "Tajikistan",
        "phonecode": "992",
        "symbol": "TJS",
		"currencyName": "Tajikistani Somoni",
    }, {
        "id": "216",
        "sortname": "TZ",
        "name": "Tanzania",
        "phonecode": "255"
    }, {
        "id": "217",
        "sortname": "TH",
        "name": "Thailand",
        "phonecode": "66",
        "symbol": "฿",
		"currencyName": "Thai Baht",
    }, {
        "id": "218",
        "sortname": "TG",
        "name": "Togo",
        "phonecode": "228",
        "symbol": "CFA",
		"currencyName": "West African CFA franc",
    }, {
        "id": "219",
        "sortname": "TK",
        "name": "Tokelau",
        "phonecode": "690",
        "symbol": "NZ$",
		"currencyName": "New Zealand Dollar",
    }, {
        "id": "220",
        "sortname": "TO",
        "name": "Tonga",
        "phonecode": "676",
        "symbol": "T$",
		"currencyName": "Tongan Paʻanga",
    }, {
        "id": "221",
        "sortname": "TT",
        "name": "Trinidad And Tobago",
        "phonecode": "1868",
        "symbol": "TT$",
		"currencyName": "Trinidad and Tobago Dollar",
    }, {
        "id": "222",
        "sortname": "TN",
        "name": "Tunisia",
        "phonecode": "216",
        "symbol": "DT",
		"currencyName": "Tunisian Dinar",


    }, {
        "id": "223",
        "sortname": "TR",
        "name": "Turkey",
        "phonecode": "90",
        "symbol": "TL",
		"currencyName": "Turkish Lira",
    }, {
        "id": "224",
        "sortname": "TM",
        "name": "Turkmenistan",
        "phonecode": "7370",
        "symbol": "T",
		"currencyName": "Turkish Lira",
    }, {
        "id": "225",
        "sortname": "TC",
        "name": "Turks And Caicos Islands",
        "phonecode": "1649",

    }, {
        "id": "226",
        "sortname": "TV",
        "name": "Tuvalu",
        "phonecode": "688"
    }, {
        "id": "227",
        "sortname": "UG",
        "name": "Uganda",
        "phonecode": "256",
        "symbol": "USh",
		"currencyName": "Ugandan Shilling",
    }, {
        "id": "228",
        "sortname": "UA",
        "name": "Ukraine",
        "phonecode": "380",
        "symbol": "₴",
		"currencyName": "Ukrainian Hryvnia",
    }, {
        "id": "229",
        "sortname": "AE",
        "name": "United Arab Emirates",
        "phonecode": "971",
        "symbol": "AED",
		"currencyName": "United Arab Emirates Dirham",
    }, {
        "id": "230",
        "sortname": "GB",
        "name": "United Kingdom",
        "phonecode": "44",
        "symbol": "£",
		"name": "British Pound Sterling",
    }, {
        "id": "231",
        "sortname": "US",
        "name": "United States",
        "phonecode": "1",
        "symbol": "$",
		"currencyName": "US Dollar",
    }, {
        "id": "232",
        "sortname": "UM",
        "name": "United States Minor Outlying Islands",
        "phonecode": "1",
        "symbol": "$",
		"currencyName": "US Dollar",
    }, {
        "id": "233",
        "sortname": "UY",
        "name": "Uruguay",
        "phonecode": "598",
        "symbol": "$U",
		"currencyName": "Uruguayan Peso",
    }, {
        "id": "234",
        "sortname": "UZ",
        "name": "Uzbekistan",
        "phonecode": "998"
    }, {
        "id": "235",
        "sortname": "VU",
        "name": "Vanuatu",
        "phonecode": "678",
        "symbol": "VT",
		"currencyName": "Vanuatu vatu",
    }, {
        "id": "236",
        "sortname": "VA",
        "name": "Vatican City State (Holy See)",
        "phonecode": "39"
    }, {
        "id": "237",
        "sortname": "VE",
        "name": "Venezuela",
        "phonecode": "58"
    }, {
        "id": "238",
        "sortname": "VN",
        "name": "Vietnam",
        "phonecode": "84",
        "symbol": "₫",
		"currencyName": "Vietnamese Dong",
    }, {
        "id": "239",
        "sortname": "VG",
        "name": "Virgin Islands (British)",
        "phonecode": "1284",
        "symbol": "$",
		"currencyName": "US Dollar",
    }, {
        "id": "240",
        "sortname": "VI",
        "name": "Virgin Islands (US)",
        "phonecode": "1340",
        "symbol": "$",
		"currencyName": "US Dollar",
    }, {
        "id": "241",
        "sortname": "WF",
        "name": "Wallis And Futuna Islands",
        "phonecode": "681",
        "symbol": "XPF",
		"currencyName": "CFP Franc",
    }, {
        "id": "242",
        "sortname": "EH",
        "name": "Western Sahara",
        "phonecode": "212"
    }, {
        "id": "243",
        "sortname": "YE",
        "name": "Yemen",
        "phonecode": "967",
        "symbol": "YR",
		"currencyName": "Yemeni Rial",
    }, {
        "id": "244",
        "sortname": "YU",
        "name": "Yugoslavia",
        "phonecode": "38"
    }, {
        "id": "245",
        "sortname": "ZM",
        "name": "Zambia",
        "phonecode": "260",
        "symbol": "ZK",
		"currencyName": "Zambian Kwacha",
    }, {
        "id": "246",
        "sortname": "ZW",
        "name": "Zimbabwe",
        "phonecode": "263",
        "symbol": "Z$",
		"currencyName": "Zimbabwean Dollar",
    }]


